### ISSUE TITLE
Getting error when executing 'just run' with a Spring Boot 2.7.5 (Kotlin) application

### ISSUE THREAD

**Issue by lucasleon2107** [maciejwalkowiak/just#24]
I'm getting this error:

```
spring | Attaching agents: []
spring | Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.boot.SpringApplicationRunListener : com.maciejwalkowiak.just.spring.boot.DevcontainersRunListener
spring |        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:449)
spring |        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:431)
spring |        at org.springframework.boot.SpringApplication.getRunListeners(SpringApplication.java:419)
spring |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:298)
spring |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
spring |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
spring |        at com.test.ApplicationKt.main(Application.kt:17)
spring | Caused by: java.lang.UnsupportedClassVersionError: com/maciejwalkowiak/just/spring/boot/DevcontainersRunListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
spring |        at java.lang.ClassLoader.defineClass1(Native Method)
spring |        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
spring |        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
spring |        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
spring |        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
spring |        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
spring |        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
spring |        at java.security.AccessController.doPrivileged(Native Method)
spring |        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
spring |        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
spring |        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
spring |        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
spring |        at java.lang.Class.forName0(Native Method)
spring |        at java.lang.Class.forName(Class.java:348)
spring |        at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
spring |        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:442)
spring |        ... 6 more
spring | ------------------------------------------------------------------------
spring | BUILD FAILURE
spring | ------------------------------------------------------------------------
spring | Total time:  16.419 s
spring | Finished at: 2022-12-23T23:39:11-05:00
spring | ------------------------------------------------------------------------
```

**Comment by maciejwalkowiak** [comment]
I see you're using Java 8. Just requires Java 11+

**Comment by lucasleon2107** [comment]
Now I'm using 'just run' with a Spring Boot 3.0.1 application with Java 17 and I'm getting a similar error

```
spring | [WARNING] Error injecting: org.springframework.boot.maven.RunMojo
spring | java.lang.TypeNotPresentException: Type org.springframework.boot.maven.RunMojo not present
spring |     at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:147)
spring |     at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
spring |     at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
spring |     at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
spring |     at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
spring |     at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
spring |     at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
spring |     at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
spring |     at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
spring |     at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
spring |     at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
spring |     at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
spring |     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
spring |     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
spring |     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
spring |     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
spring |     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
spring |     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
spring |     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
spring |     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
spring |     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
spring |     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
spring |     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
spring |     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
spring |     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
spring |     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
spring |     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
spring |     at java.lang.reflect.Method.invoke (Method.java:498)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
spring |     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
spring |     at java.lang.reflect.Method.invoke (Method.java:498)
spring |     at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:47)
spring |     at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:156)
spring |     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:72)
spring | Caused by: java.lang.UnsupportedClassVersionError: org/springframework/boot/maven/RunMojo has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
spring |     at java.lang.ClassLoader.defineClass1 (Native Method)
spring |     at java.lang.ClassLoader.defineClass (ClassLoader.java:756)
spring |     at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
spring |     at java.net.URLClassLoader.defineClass (URLClassLoader.java:473)
spring |     at java.net.URLClassLoader.access$100 (URLClassLoader.java:74)
spring |     at java.net.URLClassLoader$1.run (URLClassLoader.java:369)
spring |     at java.net.URLClassLoader$1.run (URLClassLoader.java:363)
spring |     at java.security.AccessController.doPrivileged (Native Method)
spring |     at java.net.URLClassLoader.findClass (URLClassLoader.java:362)
spring |     at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf (ClassRealm.java:425)
spring |     at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:42)
spring |     at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
spring |     at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
spring |     at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
spring |     at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:139)
spring |     at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
spring |     at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
spring |     at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
spring |     at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
spring |     at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
spring |     at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
spring |     at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
spring |     at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
spring |     at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
spring |     at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
spring |     at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
spring |     at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
spring |     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
spring |     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
spring |     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
spring |     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
spring |     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
spring |     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
spring |     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
spring |     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
spring |     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
spring |     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
spring |     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
spring |     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
spring |     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
spring |     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
spring |     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
spring |     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
spring |     at java.lang.reflect.Method.invoke (Method.java:498)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
spring |     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
spring |     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
spring |     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
spring |     at java.lang.reflect.Method.invoke (Method.java:498)
spring |     at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:47)
spring |     at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:156)
spring |     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:72)
```
