### ISSUE TITLE
Container with name 'favicon.ico' not supported

### ISSUE THREAD

**Issue by zelaskoa** [maciejwalkowiak/just#41]
When  i try to open swagger ui i get error

java.lang.RuntimeException: Container with name 'favicon.ico' not supported
        at com.maciejwalkowiak.just.web.ContainerController.lambda$createContainer$0(ContainerController.java:30)
        at java.base@17.0.5/java.util.Optional.orElseThrow(Optional.java:403)
        at com.maciejwalkowiak.just.web.ContainerController.createContainer(ContainerController.java:30)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)

**Comment by maciejwalkowiak** [comment]
Fixed in 0.13.0.

Btw, what Swagger UI are you trying to open?
