### ISSUE TITLE
Support for multi-module maven project

### ISSUE THREAD

**Issue by arey** [maciejwalkowiak/just#42]
I've tried the 0.0.13 version including the "Support for multi-module maven project" feature #18
From my application based on the hexagonal architecture I got a NullPointerException

My maven modules look like :
- pom.xml : main pom reactor
- myapp-adapter : sub-pom reactor
  - myapp-api-rest
  - myapp-customer
- myapp-application : main-module
- myapp-domain
```
just run myapp-application
...
just   | Just 0.13.0
just   | License valid until 2023-04-30
just   | Build tool: Maven
just   | Docker Compose file: docker-compose.yml not found
just   | Live Reload support is enabled
just   | Zero Config Infrastructure Services support is enabled
just   | Starting Spring Boot Application
Rewriting modules: path . modules to skip: myapp-application
Rewriting modules: path .\myapp-adapter modules to skip: myapp-application
just   | Executing command: null spring-boot:run -f .\.pom.xml.temp -Dmaven.test.skip=true -Dspring-boot.run.arguments=--just.port=4242 --just.run.live-reload.browser.enabled=true -pl myapp-application --also-make
just   | Sorry, something went wrong
java.lang.NullPointerException: null
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1092)
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at com.maciejwalkowiak.just.core.process.ProcessExecutor.execute(ProcessExecutor.java:35)
        at com.maciejwalkowiak.just.command.run.maven.Maven.execute(Maven.java:26)
        at com.maciejwalkowiak.just.command.run.maven.SpringBootRun.run(SpringBootRun.java:67)
        at com.maciejwalkowiak.just.command.run.maven.MultiModuleRunner.run(MultiModuleRunner.java:42)
        at com.maciejwalkowiak.just.command.run.RunCommand.execute(RunCommand.java:103)
        at com.maciejwalkowiak.just.command.BaseCommand.call(BaseCommand.java:49)
        at com.maciejwalkowiak.just.command.BaseCommand.call(BaseCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.maciejwalkowiak.just.PicoCliRunner.run(PicoCliRunner.java:24)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
        at com.maciejwalkowiak.just.Just.runSpringApp(Just.java:60)
        at com.maciejwalkowiak.just.Just.main(Just.java:43)
java.lang.RuntimeException: java.lang.NullPointerException
        at com.maciejwalkowiak.just.command.BaseCommand.call(BaseCommand.java:52)
        at com.maciejwalkowiak.just.command.BaseCommand.call(BaseCommand.java:16)
```

**Comment by maciejwalkowiak** [comment]
Thanks @arey for reporting. Will take a look.

**Comment by KylinChan** [comment]
I have a similar problem, in my multi-module project, the directory structure is similar to the following:

- parent: main module to depend on 
    - pom.xml (No directory such as src)
- rest: main starter module with application.class 
    - pom.xml
- api: external interface module 
    - pom.xml
- service: api implementation module
    - pom.xml
- pom.xml : main pom reactor 

The error I get when I try to run the `just run rest` command is:
```
java.nio.file.NoSuchFileException: /xxx/parent/src/main
        at java.base@17.0.5/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base@17.0.5/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base@17.0.5/java.nio.file.Files.walkFileTree(Files.java:2804)
        at java.base@17.0.5/java.nio.file.Files.walkFileTree(Files.java:2882)
        at io.methvin.watcher.PathUtils.recursiveVisitFiles(PathUtils.java:108)
        at io.methvin.watcher.PathUtils.initWatcherState(PathUtils.java:78)
        at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:190)
        at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:122)

```
In fact I don't need to create the `src` directory in  the `parent` module. 

I tried to start `just run rest` after creating the `src` directory but there are also errors:
```
spring | ------------------------------------------------------------------------
spring | [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.2.RELEASE:run (default-cli) on project parent: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
spring | [ERROR] 
spring | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
spring | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
spring | [ERROR] 
spring | [ERROR] For more information about the errors and possible solutions, please read the following articles:
spring | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
spring | [ERROR] 
spring | [ERROR] After correcting the problems, you can resume the build with the command
spring | [ERROR]   mvn <args> -rf :parent

```
It looks like I'm looking for the startup class in the `parent` module, but actually my startup class is in the `rest` module.
